version: '3.1'

services:
    proxy:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    webserver:
        build: ./project
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}

    postgres:
        image: postgres:9
        volumes:
            - ${DB_PATH_HOST}:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_PASSWORD: example

    adminer:
        image: adminer
        ports:
            - "8080:8080"

    composer:
        image: composer
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install